version: "3"
services:
  opentelemetry-collector-contrib:
    image: otel/opentelemetry-collector-contrib-dev:77a38a736cee799425bc1634126da8df7d113134
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
      - ./varlogpods:/var/log/pods